name: "{{SERVICE}}"

on:
  push:
    paths:
      - "services/{{SERVICE}}/**"
      - ".github/workflows/{{SERVICE}}.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: WORK WORK
        run: |-
          cd services/{{SERVICE}}
          npm ci
          npm test
