name: "{{SERVICE}}"

on:
  push:
    paths:
      - "services/{{SERVICE}}/**"
      - ".github/workflows/{{SERVICE}}.yml"

defaults:
  run:
    working-directory: "services/{{SERVICE}}"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install root dependencies
        working-directory: "services/{{SERVICE}}"
        run: npm ci

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
