name: "{{SERVICE}}"

on:
  push:
    paths:
      - "services/{{SERVICE}}/**"
      - ".github/workflows/{{SERVICE}}.yml"

jobs:
  defaults:
    working-directory: "services/{{SERVICE}}"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
