name: "divide"

on:
  push:
    paths:
      - "services/divide/**"
      - ".github/workflows/divide.yml"

jobs:
  defaults:
    working-directory: "services/divide"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
